# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!
workspace 'mypokemon'

target 'mypokemon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mypokemon
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
  pod 'Kingfisher'
  pod 'Alamofire', '5.4.4'
  pod 'RxSwift'
  pod 'RxCocoa'

end

target 'core' do
  project '../core/core'

  pod 'Alamofire', '5.4.4'
end 
